### ISSUE TITLE
Open source the project

### ISSUE THREAD

**Issue by mholt** [timelinize/timelinize#1]
I've been working on this project for over 10 years, and although prior, less mature forms of it have been open source over the years ([Photobak](https://github.com/mholt/photobak), [Timeliner](https://github.com/mholt/timeliner)), Timelinize was originally started as proprietary. Not to become a VC-funded capitalist venture, but mainly to preserve the IP of a complex, ambitious project that I've worked hard on for many years, especially considering its unique scope and to capture the lifetime of value it provides users.

While I mainly needed this for my own family, I wanted others with similar values to be able to use it too, but in a sustainable and supported way. The plan was to provide a very generous, time-unlimited free tier to allow people to get a solid feel for the program with the only restriction being how many items can be imported. I would then charge only a one-time fee or a subscription to be able to keep the project sustainable.

But I've felt a lot of pressure when I started building the UI because, heh, it's a lot of work. I can handle the backend, but there's so much to do for the front-end.

I thought about just open-sourcing the front-end so others could contribute, but considering I want this program to be able to reach broad non-technical audiences, it seemed weird to charge for the technical portion (the backend and CLI), and leave the user-friendly part (the UI) to be free and accessible. So you'd need to buy the backend, then download the free front-end separately. It felt the same as those apps that are free to download but you have to have another paid app or service before you can use it. Plus, with this being client software that runs in countless environments, not server software that runs on... essentially Linux, the same, everywhere, there's a lot more bugs and troubleshooting that are sure to happen.

What really tipped me over the edge to do this is realizing that this doesn't have commercial utility. In fact, I don't want businesses to use or get gain from this. I probably can't make a living from this, let alone build a business on it, because the market is consumers, and I'd need either (tens of) thousands of users or to make the software very expensive. And I can't support that many users myself, and without a business plan, I can't add employees.

So I think it only makes sense to make it open source. It's not near finished yet, and I do worry about its sustainability... so I may still ask for donations, as it has been a _lot_ of work to even get it to this point.

I hope the community will rally around the project to help fix bugs and build out great features. Keep it alive, keep it useful, and let's keep our lives and memories preserved.

**Comment by mholt** [comment]
Published, but now I need to make an intro/demo video and add screenshots before I share/publicize it.

**Comment by geekodour** [comment]
Thanks @mholt for all your work here. Excited for the future of this project. I've long been waiting for this project to become public(commercially) but since now you're made it open source I am sure it should be useful in more interesting ways. Will try out and try contributing wherever I can. kudos!

**Comment by mholt** [comment]
Thank you @geekodour! Hope to see you around the project then.
