### ISSUE TITLE
Bumped libheif 1.18 breaks Ubuntu and Fedora builds

### ISSUE THREAD

**Issue by rubiojr** [timelinize/timelinize#18]
Nothing wrong with it, but wanted to report than [bumping libheif](https://github.com/timelinize/timelinize/commit/b7cd2ae2a7b7887bc5325cbd1795aa98f59960ee) to 1.18 breaks builds (some symbols not available) in latest Fedora [and most likely Ubuntu](https://packages.ubuntu.com/search?keywords=libheif&searchon=names&suite=noble&section=all), as that libheif version isn't readily available there.

```
❯ CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build
# github.com/strukturag/libheif/go/heif
../../../go/pkg/mod/github.com/strukturag/libheif@v1.18.2/go/heif/heif.go:58:28: could not determine kind of name for C.heif_compression_HTJ2K
../../../go/pkg/mod/github.com/strukturag/libheif@v1.18.2/go/heif/heif.go:270:43: could not determine kind of name for C.heif_suberror_Camera_extrinsic_matrix_undefined
../../../go/pkg/mod/github.com/strukturag/libheif@v1.18.2/go/heif/heif.go:268:43: could not determine kind of name for C.heif_suberror_Camera_intrinsic_matrix_undefined
../../../go/pkg/mod/github.com/strukturag/libheif@v1.18.2/go/heif/heif.go:281:35: could not determine kind of name for C.heif_suberror_Compression_initialisation_error
../../../go/pkg/mod/github.com/strukturag/libheif@v1.18.2/go/heif/heif.go:272:37: could not determine kind of name for C.heif_suberror_Decompression_invalid_data
../../../go/pkg/mod/github.com/strukturag/libheif@v1.18.2/go/heif/heif.go:324:33: could not determine kind of name for C.heif_suberror_Invalid_J2K_codestream
../../../go/pkg/mod/github.com/strukturag/libheif@v1.18.2/go/heif/heif.go:328:22: could not determine kind of name for C.heif_suberror_No_icbr_box
../../../go/pkg/mod/github.com/strukturag/libheif@v1.18.2/go/heif/heif.go:314:27: could not determine kind of name for C.heif_suberror_No_ispe_property
../../../go/pkg/mod/github.com/strukturag/libheif@v1.18.2/go/heif/heif.go:254:39: could not determine kind of name for C.heif_suberror_No_matching_decoder_installed
../../../go/pkg/mod/github.com/strukturag/libheif@v1.18.2/go/heif/heif.go:326:21: could not determine kind of name for C.heif_suberror_No_vvcC_box
../../../go/pkg/mod/github.com/strukturag/libheif@v1.18.2/go/heif/heif.go:340:48: could not determine kind of name for C.heif_suberror_Unsupported_generic_compression_method
```

**Comment by mholt** [comment]
Ah, dangit. I upgraded it because the system I use (Arch) is already running the new version. It has some good fixes...

I don't know Ubuntu and Fedora well enough to know if there's a way to make it use libheif 1.18. If I downgrade it then it won't work on my Arch system :upside_down_face:

**Comment by rubiojr** [comment]
Yeah not trivial it seems 😄 

Tried vendoring libheif, but it ain't that easy because libvips depends on it, so we can't easily use libvips from the system and a vendored libheif, and vendoring+building libvips is a whole different yak shaving exercise 😄

**Comment by mholt** [comment]
Oof, that's true. Should I revert the upgrade I wonder? And wait until more distros get 1.18? (Kind of bummed they didn't make it 2.0 but oh well)

Course then I have to downgrade mine which on Arch is not ideal

**Comment by rubiojr** [comment]
Good question. I can resort to building and running with Docker while distros catch up, but adding Docker layering isn't everybody's favorites or the fastest dev feedback cycle 😄  (maybe Nix?). Here's my quick Dockerfile in case it helps:

```Dockerfile
FROM archlinux:latest
RUN	 pacman -Syy
RUN	 pacman -S --noconfirm libvips go base-devel lcms2 libheif openjpeg2 ffmpeg

# Expose tcp port
EXPOSE	12002 
WORKDIR /app
COPY . /app

ENV CGO_ENABLED=1
RUN go build -o /app/timelinize

## Fake xdg-open which doesn't work inside Docker containers out of the box
RUN echo '#!/bin/sh' > /usr/bin/xdg-open
RUN echo true >> /usr/bin/xdg-open
RUN chmod +x /usr/bin/xdg-open

VOLUME /repos

CMD	 ["/app/timelinize"]
```

Seems to work, but largely untested.

Something I noticed is that failing to open a browser is fatal (via `xdg-open`), and that doesn't play well with Docker images, so we may want to treat that as a non fatal error or make it optional. Also required a small patch to change listening address:

```diff
❯ git diff
diff --git a/tlzapp/app.go b/tlzapp/app.go
index 958e1da..eeee58c 100644
--- a/tlzapp/app.go
+++ b/tlzapp/app.go
@@ -430,4 +430,4 @@ func (vrw *virtualResponseWriter) Write(data []byte) (int, error) {
        return vrw.body.Write(data)
 }

-const defaultAdminAddr = "127.0.0.1:12002"
+const defaultAdminAddr = ":12002"
```

**Comment by mholt** [comment]
Thank you for creating and sharing that :pray: 

I hope it will only be needed for a short time!

As for `xdg-open`, if you run the program with the `serve` subcommand, i.e. `timelinize serve`, then it won't try to open a browser window.

**Comment by rubiojr** [comment]
> As for xdg-open, if you run the program with the serve subcommand, i.e. timelinize serve, then it won't try to open a browser window.

Ah! missed that!

**Comment by rubiojr** [comment]
https://pkgs.org/search/?q=libheif seems to be a good place to keep an eye on heif versions.

**Comment by mholt** [comment]
Nice, thanks for the link!

**Comment by rubiojr** [comment]
Quick note so we don't forget: I'm adding workarounds to workflow files ([like this](https://github.com/timelinize/timelinize/blob/55b503ae4d0391059d1bb4d5a4c455c9e840125c/.github/workflows/go-linter.yml#L41)) to downgrade heif while it's not available in the Ubuntu PPA. Would be worth revisiting this once the PPA has libheif 1.18.X packages.

**Comment by mholt** [comment]
@rubiojr As it so happens I encountered a strange issue with the avif decoder in libheif which resulted in this:

![Green image](https://pbs.twimg.com/media/GeFvhWTakAIImrC?format=jpg&name=900x900)

I suspect that this might have to do with something on my system being out of whack (like a libheif dependency, I read something about aom but I dunno what that is).

But I switched to a different avif decoder and libheif no longer appears in our go.mod, and thumbnails still seem to be generated pretty quickly, so maybe this is a non-issue at this point?

Still, I like libheif and probably want to switch back someday as it seems more supported.

**Comment by rubiojr** [comment]
Let me double check and share my findings 🔙

**Comment by rubiojr** [comment]
@mholt I've been able to `go build` today without issues using the latest Fedora amd64 available (F41), so not any issue here anymore 🏆

**Comment by mholt** [comment]
@rubiojr Thanks for the update! I'm also using a different AVIF encoder/decoder now: https://github.com/gen2brain/avif -- but I have a hunch that libheif is better supported/maintained, so maybe we'll switch back someday.
