### ISSUE TITLE
[question] content addressable storage for pictures

### ISSUE THREAD

**Issue by rubiojr** [timelinize/timelinize#19]
Was it considered using content addressable storage for pictures (maybe other media/files) and store image files named after the file SHA256 (or other hashing) so there's no need to check the database for file deduplication and/or verification?

**Comment by rubiojr** [comment]
@mholt probably not much with Timelinize being open source and in its current form. It's just a matter of preference that I enjoy being able to checksum files or deduplicate them without relying on additional tools, metadata of file system features. My picture filenames generally don't say much, so having a SHA256 instead of `IMG_6191` has some benefits for my worflows/scripts 😄 .

**Comment by mholt** [comment]
I see; I guess I still view CAS as needing extra tooling since you have to have scripts/programs to use it, even to compute the hash. And if the image file changes by a single byte the whole file name is completely different.

I suppose if you really want that we could make it an option but it would be a bit tedious to implement.

**Comment by rubiojr** [comment]
> I suppose if you really want that we could make it an option but it would be a bit tedious to implement.

Mostly interested in understanding the rational behind the `data/` directory files naming. The current approach works equally well for me, now that I understand that metadata is present in the sqlite database.

A question I have though, about an edge case. Given two files with the same name, without a file extension but different content (i.e. an image and a nmea log file both named `file1` for example), how would Timelinize handle that if both files end up with the same Timestamp and thus meant to be stored in the same `<year>/<month>/<day>` directory? Or is the plan to store different content in different base directories? Maybe being a small text file could end up in the database and no external file is required?

**Comment by mholt** [comment]
I figured organizing files by their year/month made the most sense for intuitive exploration without extra tooling.

But yes! The sqlite DB has a hash of the contents as well as a hash of the _original_ file contents in case it gets updated later (it's also useful for detecting duplicates during imports from data sources where an item may have been updated after it was imported, to avoid duplicating it).

> A question I have though, about an edge case. Given two files with the same name, without a file extension but different content (i.e. an image and a nmea log file both named file1 for example), how would Timelinize handle that if both files end up with the same Timestamp and thus meant to be stored in the same <year>/<month>/<day> directory?

This happens quite often; Timelinize will append a few random characters to the end of the filename to make it unique:

https://github.com/timelinize/timelinize/blob/10af144f0e43df91a05f5d4049bbcf4a01be9be6/timeline/itemfiles.go#L299-L304

> Maybe being a small text file could end up in the database and no external file is required?

Yep, this is the current behavior. Only binary files or large text files are stored separately; small text files (under 1 MB, an arbitrary size I chose) are stored directly in the DB.

**Comment by rubiojr** [comment]
Superb, thank you for the enlightenment.

**Comment by mholt** [comment]
No problem, these are great questions.

I'll also add that one design philosophy for this project is that the database is the ultimate source of truth. So the filenames may ultimately be random on disk (especially if a piece of data didn't have a filename in the first place), but if the database entry doesn't exist for it, the item doesn't exist as far as the program is concerned. The DB Knows All.
