### ISSUE TITLE
Strava Takeout silently fails

### ISSUE THREAD

**Issue by mbolli** [timelinize/timelinize#25]
My Strava Takeout `export_26969014.zip` is detected as a strava file, however, importing it silently fails with the following log message:

```log
2024/08/18 09:07:20.013 ERROR   job_manager     end     {"id": "df303208488c5dfbd12bf06de8113715ef8ca2ad98cc3fb1da59b656f605e94a", "type": "import", "parameters": {"repo":"674656d5-cf17-40bd-9e15-d43162c072bf","resume_import_id":0,"data_source_name":"strava","filenames":["/repos/export_26969014.zip"],"processing_options":{"timeframe":{},"item_unique_constraints":{"classification_name":true,"data":true,"filename":true,"location":true,"timeframe":true,"timespan":true,"timestamp":true}},"job_id":"df303208488c5dfbd12bf06de8113715ef8ca2ad98cc3fb1da59b656f605e94a"}, "duration": 0.010836243, "error": "import: decoding next XML token: XML syntax error on line 1: invalid character entity & (no semicolon)"}
```

Not sure if it is connected to #13, as in the export archive I indeed have some `.fit.gz` files in my `activities` folder (although I never had an Apple Watch). They are probably from an import of my Endomondo activities.

Ok, it's definitely the same issue as #13, sorry and please merge ;)

**Comment by mholt** [comment]
Ah no worries -- I just had not encountered .fit files before!

Contributions welcomed of course. If a sample is uploaded I may be able to work on it but it'll take longer than someone contributing it themselves I think. 😅
